[package]
name = "vantor-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "vantor"
path = "src/main.rs"

[dependencies]
vantor-core = { path = "../vantor-core" }
vantor-lexer = { path = "../vantor-lexer" }
vantor-parser = { path = "../vantor-parser" }
vantor-analysis = { path = "../vantor-analysis" }
vantor-codegen = { path = "../vantor-codegen" }
clap.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true

[build-dependencies]
