[package]
name = "vantor-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
vantor-core = { path = "../vantor-core" }
vantor-lexer = { path = "../vantor-lexer" }
thiserror.workspace = true
anyhow.workspace = true

[lib]
name = "vantor_parser"
