[package]
name = "vantor-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
vantor-core = { path = "../vantor-core" }
vantor-parser = { path = "../vantor-parser" }
thiserror.workspace = true
anyhow.workspace = true

[lib]
name = "vantor_analysis"
